package com.example.bookingkhachsan.service;

import com.example.bookingkhachsan.dto.BookingDto;
import com.example.bookingkhachsan.entity.*;
import com.example.bookingkhachsan.repository.*;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;

import java.util.List;

@Service
@RequiredArgsConstructor
public class BookingService {

    private final PhieuDatPhongRepository bookingRepo;
    private final PhongRepository phongRepo;
    private final NguoiDungRepository userRepo;
    private final DichVuRepository dichVuRepo;
    private final ChiTietSuDungDVRepository ctsdRepo;
    private final PhuThuRepository phuThuRepo;

    public PhieuDatPhong createBooking(BookingDto.CreateBookingRequest request) {
        // Validation: Check if room is available
        long overlap = bookingRepo.countOverlappingBookings(request.getPhongId(), request.getNgayDen(), request.getNgayDi());
        if (overlap > 0) {
            throw new RuntimeException("Phòng đã được đặt trong khoảng thời gian này.");
        }

        PhieuDatPhong booking = new PhieuDatPhong();
        booking.setNgayDen(request.getNgayDen());
        booking.setNgayDi(request.getNgayDi());
        
        Phong phong = phongRepo.findById(request.getPhongId())
                .orElseThrow(() -> new RuntimeException("Room not found"));
        booking.setPhong(phong);
        booking.setGiaPhongGoc(phong.getGiaTien()); // Snapshot price
        
        // Spec says: "ma_dat_phong, trang_thai... generated by Trigger/Default"
        // Also "nguoi_dung_id" is needed. Assuming passed in request or from context.
        // For MVP, passing in request.
        NguoiDung user = userRepo.findById(request.getNguoiDungId())
                .orElseThrow(() -> new RuntimeException("User not found"));
        booking.setNguoiDung(user);
        
        booking.setThanhTien(BigDecimal.ZERO); // Trigger or logic update? Trigger does NOT calculate thanh_tien initially?
        // Trigger trg_GenerateBookingCode sets thanh_tien from inserted i.
        // So we must set it. Logic: (Days * Price). 
        // But let's set 0 and let DB/Logic handle or calculate simple.
        // Spec: "Dev không được tự tính tổng tiền bằng code ở Backend (cho checkout)". 
        // Initialize with basic room cost?
        // Let's set it to giaPhong * days.
        long days = java.time.temporal.ChronoUnit.DAYS.between(request.getNgayDen(), request.getNgayDi());
        if (days < 1) days = 1;
        booking.setThanhTien(phong.getGiaTien().multiply(BigDecimal.valueOf(days)));

        return bookingRepo.save(booking);
    }

    public PhieuDatPhong getBooking(String code) {
        return bookingRepo.findByMaDatPhong(code)
                .orElseThrow(() -> new RuntimeException("Booking not found"));
    }

    public void checkin(Integer id) {
        PhieuDatPhong booking = bookingRepo.findById(id).orElseThrow();
        booking.setTrangThai("Đã checkin");
        bookingRepo.save(booking);
    }

    @Transactional
    public void checkout(Integer id) {
        bookingRepo.checkout(id);
    }

    public void addService(BookingDto.AddServiceRequest request) {
        PhieuDatPhong booking = bookingRepo.findById(request.getPhieuDatPhongId()).orElseThrow();
        DichVu dv = dichVuRepo.findById(request.getDichVuId()).orElseThrow();
        
        ChiTietSuDungDV ct = new ChiTietSuDungDV();
        ct.setPhieuDatPhong(booking);
        ct.setDichVu(dv);
        ct.setSoLuong(request.getSoLuong());
        ct.setDonGiaLucDat(dv.getGiaTien());
        
        ctsdRepo.save(ct);
    }

    public void addSurcharge(BookingDto.AddSurchargeRequest request) {
        PhieuDatPhong booking = bookingRepo.findById(request.getPhieuDatPhongId())
                .orElseThrow(() -> new RuntimeException("Booking not found"));
        // Implementation for adding surcharge would go here (saving to new entity or updating total)
        // For now just simpler placeholder or omitted as per instructions focus
        PhuThu pt = new PhuThu();
        pt.setPhieuDatPhong(booking);
        pt.setLoaiPhuThu(request.getLoaiPhuThu());
        pt.setSoTien(request.getSoTien());
        
        phuThuRepo.save(pt);
    }

    public List<PhieuDatPhong> getBookingsByUser(Integer userId) {
        return bookingRepo.findByNguoiDungId(userId);
    }
}
